### PR TITLE
QA of v201601 migration

### PR DESCRIPTION
**Pull request by christianblunden**
removed deleted columns and ensure parity between docs and adworj report definition columns

### CODE REVIEW

**Comment by christianblunden** [comment]
@pingles you happy me for me to merge this and bump the version?

there will be breaking changes.. so I guess a full major version?

**Comment by christianblunden** [comment]
v201603 to follow...

**Comment by pingles** [comment]
A big change is fine. But, there's a few places where the `Money` types should be parsed as longs rather than doubles though? 

From what I can find in the docs these should be money types (and so parsed as longs):
- `CostPerConversion`
- `CostPerConvertedClick`

Do you want to push to a branch and I can help out or are you happy to just update the few places where the conversion is done? There's some reports where no parsing is done so I guess for now we could just concentrate on the ones where its using `parse-double` instead of `parse-long`?

Major bump is good. @sdawara and I updated the conversion ns earlier to v201601 too.

Thanks for picking this up :)

**Comment by christianblunden** [comment]
ok I'll double check the money types.. and I'll push the v201603 branch shortly.. I basically branched it from the v201601fixes branch so they should all merge nicely ;)

**Comment by pingles** [comment]
👍

**Pull request merged**
